### ISSUE TITLE
Review of Problem Statement

### ISSUE THREAD

**Issue by yanxuanm** [yanxuanm/CAS741#2]
@smiths 

Hi Dr. Spencer Smith, 

This issue is created for reviewing the problem statement of CAS741.

**Comment by smiths** [comment]
Thank you @yanxuanm.  I have the following feedback for you:

- when there is a file you would like to have reviewed, please include a link to the file. 
- I see that you have copied the full blank project template.  That is fine, but please check as we reach each deliverable, since I am likely to modify the templates as the term goes along
- for the problem statement, please clarify the scope further.  The finite element method is a great topic, but too broad.  You mentioned solving for displacements at the end, but, as written, it isn't entirely clear that this is your scope.  Rather than characterizing the problem as solving for displacement, you should say that you are solving linear elasticity problems in two dimensions.  (If you had a different scope in mind, that is fine, as long as it isn't too ambitious.)

I had a student do a finite element project in the past.  He did a nice job on the SRS.  I'll e-mail you the document.

Once you have refined the scope (last paragraph of your statement), please let me know.  I'll officially approve the project once that clarification is made.

**Comment by yanxuanm** [comment]
Hi Dr. @smiths , 

Thanks for your comment, I have narrow down the scope of my PS, I am thinking of using FEM as an algorithem for solving phsically-based simulation problems in computer graphics. Particulaly, 2d and 3d elasticity deformations. 

This is the file to review.  https://github.com/yanxuanm/CAS741/blob/master/ProblemStatement/ProblemStatement.pdf


Thanks
Xuanming Yan

**Comment by smiths** [comment]
@yanxuanm, I will approve your problem statement.  However, we will need to be careful as you work on your SRS.  We do not want the scope to be too large.  Also, we want to find the appropriate level of abstraction.

The particular points to keep in mind when working on your SRS:

- have your goal statement related to your calculations, not to displaying the results -  you can bring up how you will display the results in the requirements section.
- the output should be the displacements at the nodes - you can make a requirement of displaying the deformed mesh, but the primary output is the displacements
- in your SRS be careful to not cover aspects of the finite element method that are not necessary at the requirements stage.  The SRS should cover the physics of the problem and the mathematics of FEM, but not details of algorithms, unless you have a specific requirement to change a design decision within a set of design decisions (as Leila is doing).  There will also be a design document coming up.  You will cover design decisions at this point.
