### ISSUE TITLE
SRS Review

### ISSUE THREAD

**Issue by yanxuanm** [yanxuanm/CAS741#4]
Hi, @smiths, @moalaa, @JohnErnsthausen

I have competed the SRS docuemnts. 

https://github.com/yanxuanm/CAS741/blob/master/SRS/SRS.pdf

Thanks
Xuanming

**Comment by yanxuanm** [comment]
follow up with @JohnErnsthausen

**Comment by JohnErnsthausen** [comment]
Thank you, @yanxuanm. I am reviewing your SRS document. I missed the part about the Repos.xlsx update, and as a result misunderstood the reviewer process. I now see I was assigned as your "Domain Expert". I'll do my best. I'll address this issue promptly.

**Comment by JohnErnsthausen** [comment]
Hello, @yanxuanm. I completed my review of your SRS document. However, I cannot close this issue. Please let me know how to close this issue. Thank you.

**Comment by smiths** [comment]
In commit fc5936e I've made some spelling mistake corrections.  The SRS currently does not compile.  Please add the missing figure under version control and fix the error messages.  You should also modify your `.gitignore` file so that the following files are ignored `*.aux, *.log, *.out` etc.  You can look at the original blank project template to see sample `.gitignore` files.

**Comment by smiths** [comment]
Feedback on the SRS is given in commit ec8615a.  Please create issues as appropriate.
